#!/bin/bash

set -e
set -o pipefail

# Set this constant with the tag name corresponding to the image version you wish to use for the scan
# (for a list of tags visit: https://hub.docker.com/r/meterian/cli/tags)
VERSION="latest"
DOCKER_FULL_IMAGE_NAME="meterian/cli:${VERSION}"
WORKDIR=${METERIAN_WORKDIR:-$(pwd)}
echo "Current work directory: ${WORKDIR}"
echo "Contents of ${WORKDIR}"
ls ${WORKDIR}

# in this occasion utilise the client canary for the scan
if [[ "$*" =~ "--canary" ]];
then
    CLIENT_CANARY_FLAG=on
    DOCKER_FULL_IMAGE_NAME="meterian/cli-canary:${VERSION}"
    echo "Using canary version of Docker and Meterian clients"
fi

if [[ "$*" =~ "--unbound" ]];
then
    docker run --rm \
              --volume ${WORKDIR}:/workspace \
              --env METERIAN_API_TOKEN=${METERIAN_API_TOKEN} \
              --env CLIENT_VM_PARAMS=${CLIENT_VM_PARAMS} \
              --env CLIENT_CANARY_FLAG=${CLIENT_CANARY_FLAG} \
              --env GOPRIVATE=${GOPRIVATE} \
              --env CLIENT_ENV=${CLIENT_ENV} \
              --volume "${HOME}/.netrc":"/home/meterian/.netrc" \
              ${DOCKER_FULL_IMAGE_NAME} $*

    # please do not add any command after "docker run" as we need to preserve
    # the exit status of the meterian client

else

    # get current uid
    HOST_UID=`id -u`
    HOST_GID=`id -g`

    CONTAINER_HOME_DIR=/home/meterian

    VOLUME_BINDS=(
        "$HOME/.cache::$CONTAINER_HOME_DIR/.cache"
        "$HOME/.local::$CONTAINER_HOME_DIR/.local"
    # maven specific mappings
        "$HOME/.m2::$CONTAINER_HOME_DIR/.m2"
    # dotnet specific mappings
        "$HOME/.dotnet::$CONTAINER_HOME_DIR/.dotnet"
        "$HOME/.nuget::$CONTAINER_HOME_DIR/.nuget"
    # gradle specific mappings
        "$HOME/.gradle::$CONTAINER_HOME_DIR/.gradle"
    # sbt specific mappings
        "$HOME/.sbt::$CONTAINER_HOME_DIR/.sbt"
        "$HOME/.ivy2::$CONTAINER_HOME_DIR/.ivy2"
    )

    set +e
    cache_dir=$(gem environment gemdir 2>/dev/null)
    if [ $? -eq 0 ];
    then
        VOLUME_BINDS=( "${VOLUME_BINDS[@]}" "${cache_dir}::/var/lib/gems/2.5.0/cache" )
    fi

    cache_dir=$(npm root -g 2>/dev/null)
    if [ $? -eq 0 ];
    then
        VOLUME_BINDS=( "${VOLUME_BINDS[@]}" "${cache_dir}::/usr/lib/node_modules" )
    fi
    set -e

    docker_run_data=""
    for index in "${VOLUME_BINDS[@]}"; do
        local_addr="${index%%::*}"
        if [ -d $local_addr ];
        then
            docker_addr="${index##*::}"
            docker_run_data="${docker_run_data} --mount type=bind,source='${local_addr}',target='${docker_addr}' "
        fi
    done

    # mapping /tmp so that the most recent version of the meterian client is retained on the host machine causing it to be updated the least often
    docker_run_data="${docker_run_data} --mount type=bind,source=/tmp,target=/tmp "
    docker_run_data="${docker_run_data} --volume '${HOME}/.netrc':/home/meterian/.netrc"

    docker_run_data="${docker_run_data} --env HOST_UID='${HOST_UID}' --env HOST_GID='${HOST_GID}' "
    docker_run_data="${docker_run_data} --env GOPRIVATE='${GOPRIVATE}' "
    docker_run_data="${docker_run_data} --env CLIENT_ENV='${CLIENT_ENV}' "
    docker_run_data="${docker_run_data} --env METERIAN_API_TOKEN='${METERIAN_API_TOKEN}' --env CLIENT_VM_PARAMS='${CLIENT_VM_PARAMS}' --env CLIENT_CANARY_FLAG='${CLIENT_CANARY_FLAG}' '${DOCKER_FULL_IMAGE_NAME}' \$*"
    eval "docker run --rm --volume $WORKDIR:/workspace $docker_run_data"

    # please do not add any command after "docker run" as we need to preserve
    # the exit status of the meterian client

fi

# please do not add any command after "docker run" as we need to preserve
# the exit status of the meterian client
