#!/bin/bash

set -e
set -o pipefail

VERSION="0.2"
DOCKER_FULL_IMAGE_NAME="meterian/cli:${VERSION}"
WORKDIR=$(pwd)

if [[ "$*" =~ "--unbound" ]];
then
    docker run -it --rm \
              --volume ${WORKDIR}:/workspace \
              --env METERIAN_API_TOKEN=${METERIAN_API_TOKEN} \
              ${DOCKER_FULL_IMAGE_NAME} $*

    # please do not add any command after "docker run" as we need to preserve
    # the exit status of the meterian client

else

    # get current uid
    HOST_UID=`id -u`
    HOST_GID=`id -g`

    CONTAINER_HOME_DIR=/home/meterian
    docker_run_command="docker run -it --rm --volume $WORKDIR:/workspace "

    declare -A VOLUME_BINDS
    VOLUME_BINDS=(
        ["$HOME/.cache"]=$CONTAINER_HOME_DIR/.cache
        ["$HOME/.local"]=$CONTAINER_HOME_DIR/.local
    # maven specific mappings
        ["$HOME/.m2"]=$CONTAINER_HOME_DIR/.m2
    # dotnet specific mappings                            
        ["$HOME/.dotnet"]=$CONTAINER_HOME_DIR/.dotnet
        ["$HOME/.nuget"]=$CONTAINER_HOME_DIR/.nuget
        # ruby specific mappings
        [$(gem environment gemdir)/cache]=/var/lib/gems/2.3.0/cache
        # node specific mappings
        [$(npm root -g)]=/usr/lib/node_modules
    # gradle specific mappings
        ["$HOME/.gradle"]=$CONTAINER_HOME_DIR/.gradle
    # sbt specific mappings
        ["$HOME/.sbt"]=$CONTAINER_HOME_DIR/.sbt
        ["$HOME/.ivy2"]=$CONTAINER_HOME_DIR/.ivy2
    )

    for local_addr in "${!VOLUME_BINDS[@]}"; do 
        if [ -d $local_addr ];
        then
            docker_addr=${VOLUME_BINDS[$local_addr]}
            docker_run_command="$docker_run_command --mount type=bind,source=$local_addr,target=$docker_addr"
        fi
    done

    docker_run_command="$docker_run_command --env HOST_UID=$HOST_UID --env HOST_GID=$HOST_GID"
    docker_run_command="$docker_run_command --env METERIAN_API_TOKEN=$METERIAN_API_TOKEN $DOCKER_FULL_IMAGE_NAME \$*"
    eval $docker_run_command

    # please do not add any command after "docker run" as we need to preserve
    # the exit status of the meterian client

fi

# please do not add any command after "docker run" as we need to preserve
# the exit status of the meterian client
