#!/bin/bash

set -e
set -o pipefail

# Set this constant with the tag name corresponding to the image version you wish to use for the scan
# (for a list of tags visit: https://hub.docker.com/r/meterian/cli/tags)
VERSION="latest"
DOCKER_FULL_IMAGE_NAME="meterian/cli:${VERSION}"
WORKDIR=$(pwd)

if [[ "$*" =~ "--unbound" ]];
then
    docker run -it --rm \
              --volume ${WORKDIR}:/workspace \
              --env METERIAN_API_TOKEN=${METERIAN_API_TOKEN} \
              ${DOCKER_FULL_IMAGE_NAME} $*

    # please do not add any command after "docker run" as we need to preserve
    # the exit status of the meterian client

else

    # get current uid
    HOST_UID=`id -u`
    HOST_GID=`id -g`

    CONTAINER_HOME_DIR=/home/meterian

    declare -A VOLUME_BINDS
    VOLUME_BINDS=(
        ["$HOME/.cache"]=$CONTAINER_HOME_DIR/.cache
        ["$HOME/.local"]=$CONTAINER_HOME_DIR/.local
    # maven specific mappings
        ["$HOME/.m2"]=$CONTAINER_HOME_DIR/.m2
    # dotnet specific mappings                            
        ["$HOME/.dotnet"]=$CONTAINER_HOME_DIR/.dotnet
        ["$HOME/.nuget"]=$CONTAINER_HOME_DIR/.nuget
    # ruby specific mappings
        [$(gem environment gemdir)/cache]=/var/lib/gems/2.5.0/cache
    # node specific mappings
        [$(npm root -g)]=/usr/lib/node_modules
    # gradle specific mappings
        ["$HOME/.gradle"]=$CONTAINER_HOME_DIR/.gradle
    # sbt specific mappings
        ["$HOME/.sbt"]=$CONTAINER_HOME_DIR/.sbt
        ["$HOME/.ivy2"]=$CONTAINER_HOME_DIR/.ivy2
    )

    docker_run_data=""
    for local_addr in "${!VOLUME_BINDS[@]}"; do 
        if [ -d $local_addr ];
        then
            docker_addr=${VOLUME_BINDS[$local_addr]}
            docker_run_data+="--mount type=bind,source='${local_addr}',target='${docker_addr}' "
        fi
    done

    # mapping /tmp so that the most recent version of the meterian client is retained on the host machine causing it to be updated the least often 
    docker_run_data+="--mount type=bind,source=/tmp,target=/tmp "

    docker_run_data+="--env HOST_UID='${HOST_UID}' --env HOST_GID='${HOST_GID}' "
    docker_run_data+="--env METERIAN_API_TOKEN='${METERIAN_API_TOKEN}' '${DOCKER_FULL_IMAGE_NAME}' \$*"
    eval "docker run -it --rm --volume $WORKDIR:/workspace $docker_run_data"

    # please do not add any command after "docker run" as we need to preserve
    # the exit status of the meterian client

fi

# please do not add any command after "docker run" as we need to preserve
# the exit status of the meterian client